CREATE TABLE IF NOT EXISTS `platform_upgrade_runs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `repository` VARCHAR(255) NOT NULL,
  `branch` VARCHAR(128) NOT NULL DEFAULT 'main',
  `from_commit` VARCHAR(64) NOT NULL,
  `target_commit` VARCHAR(64) NOT NULL,
  `status` ENUM('scanned','approved','running','completed','failed','rolled_back') NOT NULL DEFAULT 'scanned',
  `changed_files` JSON NULL,
  `scan_summary` JSON NULL,
  `risk_summary` JSON NULL,
  `backup_filename` VARCHAR(512) NULL,
  `rollback_snapshot` VARCHAR(1024) NULL,
  `output` TEXT NULL,
  `scanned_by_user_id` INT NOT NULL,
  `approved_by_user_id` INT NULL,
  `approved_at` TIMESTAMP NULL,
  `started_at` TIMESTAMP NULL,
  `completed_at` TIMESTAMP NULL,
  `rolled_back_by_user_id` INT NULL,
  `rolled_back_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `platform_upgrade_runs_status_created_idx` (`status`, `created_at`),
  INDEX `platform_upgrade_runs_target_commit_idx` (`target_commit`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
