CREATE TABLE IF NOT EXISTS `marketing_campaigns` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `public_key` VARCHAR(32) NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `objective` VARCHAR(32) NOT NULL DEFAULT 'awareness',
  `channel` VARCHAR(32) NOT NULL DEFAULT 'website',
  `status` VARCHAR(24) NOT NULL DEFAULT 'draft',
  `audience` VARCHAR(255) NULL,
  `headline` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `cta_label` VARCHAR(96) NULL,
  `destination_url` VARCHAR(1024) NOT NULL,
  `utm_source` VARCHAR(96) NULL,
  `utm_medium` VARCHAR(96) NULL,
  `utm_campaign` VARCHAR(128) NULL,
  `utm_content` VARCHAR(128) NULL,
  `starts_at` TIMESTAMP NULL,
  `ends_at` TIMESTAMP NULL,
  `click_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `conversion_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_by_user_id` INT NOT NULL,
  `updated_by_user_id` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX `marketing_campaigns_public_key_unique` (`public_key`),
  INDEX `marketing_campaigns_status_dates_idx` (`status`, `starts_at`, `ends_at`),
  INDEX `marketing_campaigns_channel_idx` (`channel`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
