import { useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { trpc, errorMessage } from "@/lib/trpc";
import { Button } from "@/components/ui/Button";
import { FieldShell, Input, Select, Textarea } from "@/components/ui/Field";
import { Badge, Card, CardHeader, EmptyState } from "@/components/ui/Surface";
import { ConfirmDialog, Modal } from "@/components/ui/Modal";
import { PageHeader } from "@/components/layout/PortalLayout";
import { useToast } from "@/components/ui/Toast";

type Form = { id?: number; title: string; bodyMarkdown: string; audience: "all" | "customers" | "staff"; isActive: boolean; startsAt: string; endsAt: string };
const emptyForm: Form = { title: "", bodyMarkdown: "", audience: "all", isActive: true, startsAt: "", endsAt: "" };

export function AdminAnnouncementsPage() {
  const toast = useToast(); const utils = trpc.useUtils();
  const [form, setForm] = useState<Form | null>(null); const [removeId, setRemoveId] = useState<number | null>(null);
  const list = trpc.tier3.announcements.list.useQuery();
  const save = trpc.tier3.announcements.upsert.useMutation({ async onSuccess() { await utils.tier3.announcements.list.invalidate(); setForm(null); toast.success("Announcement saved"); }, onError(error) { toast.error("Could not save announcement", errorMessage(error)); } });
  const remove = trpc.tier3.announcements.remove.useMutation({ async onSuccess() { await utils.tier3.announcements.list.invalidate(); setRemoveId(null); toast.success("Announcement removed"); }, onError(error) { toast.error("Could not remove announcement", errorMessage(error)); } });
  const open = (item?: NonNullable<typeof list.data>[number]) => setForm(item ? { id: item.id, title: item.title, bodyMarkdown: item.bodyMarkdown, audience: item.audience as Form["audience"], isActive: item.isActive, startsAt: item.startsAt ? new Date(item.startsAt).toISOString().slice(0, 16) : "", endsAt: item.endsAt ? new Date(item.endsAt).toISOString().slice(0, 16) : "" } : { ...emptyForm });
  return <><PageHeader title="Portal announcements" description="Publish timely updates on the customer dashboard." actions={<Button onClick={() => open()} leadingIcon={<Plus className="size-4" />}>New announcement</Button>} />
    {(list.data ?? []).length === 0 ? <Card><EmptyState icon={Plus} title="No announcements" description="Create an announcement to communicate with customers in their portal." /></Card> : <div className="space-y-3">{(list.data ?? []).map((item) => <Card key={item.id} className="flex items-start gap-4 p-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-ink">{item.title}</p><Badge tone={item.isActive ? "success" : "neutral"}>{item.isActive ? "Active" : "Inactive"}</Badge><Badge>{item.audience}</Badge></div><p className="mt-1 whitespace-pre-wrap text-sm text-body">{item.bodyMarkdown}</p></div><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={() => open(item)} leadingIcon={<Pencil className="size-4" />}>Edit</Button><Button size="sm" variant="ghost" onClick={() => setRemoveId(item.id)} leadingIcon={<Trash2 className="size-4" />}>Delete</Button></div></Card>)}</div>}
    {form ? <Modal open onClose={() => setForm(null)} title={form.id ? "Edit announcement" : "New announcement"} size="lg"><div className="space-y-4"><FieldShell label="Title" required><Input value={form.title} onChange={(event) => setForm((value) => value && { ...value, title: event.target.value })} /></FieldShell><FieldShell label="Message" required><Textarea rows={7} value={form.bodyMarkdown} onChange={(event) => setForm((value) => value && { ...value, bodyMarkdown: event.target.value })} /></FieldShell><div className="grid gap-4 sm:grid-cols-2"><FieldShell label="Audience"><Select value={form.audience} onChange={(event) => setForm((value) => value && { ...value, audience: event.target.value as Form["audience"] })}><option value="all">All portal users</option><option value="customers">Customers</option><option value="staff">Staff</option></Select></FieldShell><FieldShell label="Status"><Select value={form.isActive ? "active" : "inactive"} onChange={(event) => setForm((value) => value && { ...value, isActive: event.target.value === "active" })}><option value="active">Active</option><option value="inactive">Inactive</option></Select></FieldShell></div><div className="grid gap-4 sm:grid-cols-2"><FieldShell label="Starts (optional)"><Input type="datetime-local" value={form.startsAt} onChange={(event) => setForm((value) => value && { ...value, startsAt: event.target.value })} /></FieldShell><FieldShell label="Ends (optional)"><Input type="datetime-local" value={form.endsAt} onChange={(event) => setForm((value) => value && { ...value, endsAt: event.target.value })} /></FieldShell></div><div className="flex justify-end gap-3"><Button variant="outline" onClick={() => setForm(null)}>Cancel</Button><Button busy={save.isPending} disabled={!form.title.trim() || !form.bodyMarkdown.trim()} onClick={() => save.mutate({ id: form.id, title: form.title, bodyMarkdown: form.bodyMarkdown, audience: form.audience, isActive: form.isActive, startsAt: form.startsAt ? new Date(form.startsAt).toISOString() : undefined, endsAt: form.endsAt ? new Date(form.endsAt).toISOString() : undefined })}>Save announcement</Button></div></div></Modal> : null}
    <ConfirmDialog open={removeId !== null} onClose={() => setRemoveId(null)} onConfirm={() => { if (removeId !== null) remove.mutate({ id: removeId }); }} title="Delete announcement?" message="This removes it from the customer portal." confirmLabel="Delete" variant="danger" busy={remove.isPending} />
  </>;
}
