import { useState } from "react";
import { Copy, Eye, FileClock, Mail, Plus, Save, Send, ShieldCheck, Trash2 } from "lucide-react";
import { trpc, errorMessage } from "@/lib/trpc";
import { Button } from "@/components/ui/Button";
import { FieldShell, Input, Select, Textarea } from "@/components/ui/Field";
import { Badge, Card, CardHeader, EmptyState, Skeleton } from "@/components/ui/Surface";
import { ConfirmDialog, Modal } from "@/components/ui/Modal";
import { PageHeader } from "@/components/layout/PortalLayout";
import { useToast } from "@/components/ui/Toast";
import { formatDateTime } from "@/lib/utils";

type Template = { templateKey: string; name: string; subject: string; bodyHtml: string; bodyText: string | null; enabled: boolean };
type EmailLog = { id: number; subject: string; templateKey: string | null; status: string; detail: string | null; createdAt: Date | string; sentAt: Date | string | null; to: string | null; bcc: string | null; bodyHtml: string | null; bodyText: string | null };
type EditState = { templateKey: string; name: string; subject: string; bodyHtml: string; bodyText: string; enabled: boolean; mode: "html" | "rich" };

export function EmailCenterPage() {
  const toast = useToast();
  const utils = trpc.useUtils();
  const templates = trpc.admin.emailTemplates.useQuery();
  const audit = trpc.admin.emailAuditSettings.useQuery();
  const history = trpc.admin.emailDeliveryHistory.useQuery({ limit: 100 });
  const [editing, setEditing] = useState<EditState | null>(null);
  const [preview, setPreview] = useState<{ subject: string; html: string } | null>(null);
  const [viewLog, setViewLog] = useState<EmailLog | null>(null);
  const [cloneSource, setCloneSource] = useState<Template | null>(null);
  const [cloneKey, setCloneKey] = useState("");
  const [cloneName, setCloneName] = useState("");
  const [auditBcc, setAuditBcc] = useState("");
  const [retentionDays, setRetentionDays] = useState("365");
  const [purgeOpen, setPurgeOpen] = useState(false);

  const update = trpc.admin.updateEmailTemplate.useMutation({ async onSuccess() { await templates.refetch(); setEditing(null); toast.success("Email template saved"); }, onError(error) { toast.error("Could not save template", errorMessage(error)); } });
  const clone = trpc.admin.cloneEmailTemplate.useMutation({ async onSuccess() { await templates.refetch(); setCloneSource(null); toast.success("Template cloned", "The copied template is disabled until you enable it."); }, onError(error) { toast.error("Could not clone template", errorMessage(error)); } });
  const saveAudit = trpc.admin.updateEmailAuditSettings.useMutation({ async onSuccess() { await audit.refetch(); toast.success("Email audit settings saved"); }, onError(error) { toast.error("Could not save audit settings", errorMessage(error)); } });
  const purge = trpc.admin.purgeEmailDeliveryHistory.useMutation({ async onSuccess(result) { await history.refetch(); setPurgeOpen(false); toast.success("Retention purge complete", `${result.deleted} retained email record(s) removed.`); }, onError(error) { toast.error("Could not purge email history", errorMessage(error)); } });

  const openEdit = (template: Template) => setEditing({ templateKey: template.templateKey, name: template.name, subject: template.subject, bodyHtml: template.bodyHtml, bodyText: template.bodyText ?? "", enabled: template.enabled, mode: "html" });
  const openClone = (template: Template) => { setCloneSource(template); setCloneKey(`${template.templateKey}_copy`.slice(0, 64)); setCloneName(`${template.name} copy`); };
  const syncAudit = () => { if (audit.data) { setAuditBcc(audit.data.auditBcc); setRetentionDays(String(audit.data.retentionDays)); } };
  if (templates.isLoading || audit.isLoading || history.isLoading) return <div className="space-y-4"><Skeleton className="h-12 w-72" /><Skeleton className="h-96 w-full" /></div>;

  return <>
    <PageHeader title="Email Template Center" description="Manage system email content, safely preview messages, retain delivery copies, and control audit BCC and retention." />
    <div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]">
      <Card><CardHeader title="System email templates" description="Templates are used for ReadyPackets customer and administrator notifications. Clone a template before creating a variant." />
        <div className="mt-4 space-y-3">{(templates.data ?? []).map((template) => <div key={template.templateKey} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-line p-4"><div className="min-w-0"><p className="font-medium text-ink">{template.name}</p><p className="mt-1 truncate text-sm text-body">{template.subject}</p><p className="mt-1 font-mono text-xs text-muted">{template.templateKey}</p></div><div className="flex flex-wrap items-center gap-2"><Badge tone={template.enabled ? "success" : "neutral"}>{template.enabled ? "Enabled" : "Disabled"}</Badge><Button size="sm" variant="outline" onClick={() => setPreview({ subject: template.subject, html: template.bodyHtml })} leadingIcon={<Eye className="size-3.5" />}>Preview</Button><Button size="sm" variant="outline" onClick={() => openClone(template as Template)} leadingIcon={<Copy className="size-3.5" />}>Clone</Button><Button size="sm" onClick={() => openEdit(template as Template)} leadingIcon={<Mail className="size-3.5" />}>Edit</Button></div></div>)}</div>
      </Card>
      <div className="space-y-6"><Card><CardHeader title="Delivery audit policy" description="Every outgoing email is retained as an encrypted audit record. The BCC address receives a blind copy of each delivery." /><div className="mt-4 space-y-4"><FieldShell label="Audit BCC email address" help="Optional. This address is BCC’d on every outgoing transactional email."><Input type="email" value={auditBcc} placeholder="archive@example.com" onFocus={syncAudit} onChange={(event) => setAuditBcc(event.target.value)} /></FieldShell><FieldShell label="Retention period (days)" help="Sent-email copies older than this period can be purged by an administrator."><Input type="number" min={7} max={3650} value={retentionDays} onFocus={syncAudit} onChange={(event) => setRetentionDays(event.target.value)} /></FieldShell><Button fullWidth busy={saveAudit.isPending} onClick={() => saveAudit.mutate({ auditBcc: auditBcc.trim(), retentionDays: Math.max(7, Math.min(3650, Number(retentionDays) || 365)) })} leadingIcon={<Save className="size-4" />}>Save delivery policy</Button></div></Card><Card><CardHeader title="Retention purge" description={`Removes retained email records older than ${audit.data?.retentionDays ?? 365} days.`} /><Button className="mt-4" variant="danger" fullWidth onClick={() => setPurgeOpen(true)} leadingIcon={<Trash2 className="size-4" />}>Purge expired email records</Button></Card></div>
    </div>
    <Card className="mt-6"><CardHeader title="Sent email history" description="Encrypted delivery copies, recipient addresses, BCC information, status, and timestamps. Existing historical hash-only logs show unavailable fields." /><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-line text-xs uppercase tracking-wide text-muted"><tr><th className="px-3 py-2">Sent</th><th className="px-3 py-2">Recipient</th><th className="px-3 py-2">Subject</th><th className="px-3 py-2">Status</th><th className="px-3 py-2" /></tr></thead><tbody>{(history.data ?? []).length ? (history.data as EmailLog[]).map((entry) => <tr key={entry.id} className="border-b border-line/70"><td className="px-3 py-3 text-xs text-muted">{formatDateTime(entry.sentAt ?? entry.createdAt)}</td><td className="px-3 py-3">{entry.to ?? "Unavailable (legacy log)"}</td><td className="max-w-xs truncate px-3 py-3">{entry.subject}</td><td className="px-3 py-3"><Badge tone={entry.status === "sent" ? "success" : entry.status === "failed" ? "danger" : "warning"}>{entry.status}</Badge></td><td className="px-3 py-3 text-right"><Button size="sm" variant="outline" onClick={() => setViewLog(entry)} leadingIcon={<FileClock className="size-3.5" />}>View</Button></td></tr>) : <tr><td colSpan={5}><EmptyState icon={Mail} title="No retained email yet" description="Sent messages will appear here after the delivery worker processes them." /></td></tr>}</tbody></table></div></Card>
    {editing ? <Modal open onClose={() => setEditing(null)} title={`Edit ${editing.name}`} size="xl" footer={<><Button variant="outline" onClick={() => setEditing(null)}>Cancel</Button><Button busy={update.isPending} disabled={!editing.subject.trim() || editing.bodyHtml.trim().length < 10} onClick={() => update.mutate({ templateKey: editing.templateKey, subject: editing.subject.trim(), bodyHtml: editing.bodyHtml, bodyText: editing.bodyText || null, enabled: editing.enabled })} leadingIcon={<Save className="size-4" />}>Save template</Button></>}><div className="space-y-4"><FieldShell label="Subject" required><Input value={editing.subject} onChange={(event) => setEditing({ ...editing, subject: event.target.value })} /></FieldShell><FieldShell label="Authoring mode"><Select value={editing.mode} onChange={(event) => setEditing({ ...editing, mode: event.target.value as "html" | "rich" })}><option value="html">HTML source</option><option value="rich">Rich text</option></Select></FieldShell>{editing.mode === "html" ? <FieldShell label="HTML email body" required><Textarea rows={16} value={editing.bodyHtml} onChange={(event) => setEditing({ ...editing, bodyHtml: event.target.value })} /></FieldShell> : <FieldShell label="Rich text email body" help="Use formatting controls in your browser; the resulting HTML is stored in the template."><div contentEditable suppressContentEditableWarning className="min-h-64 rounded-lg border border-line bg-surface p-4 text-body focus:outline-none focus:ring-2 focus:ring-teal/40" dangerouslySetInnerHTML={{ __html: editing.bodyHtml }} onInput={(event) => setEditing({ ...editing, bodyHtml: event.currentTarget.innerHTML })} /></FieldShell>}<FieldShell label="Plain-text alternative"><Textarea rows={5} value={editing.bodyText} onChange={(event) => setEditing({ ...editing, bodyText: event.target.value })} /></FieldShell><div className="flex gap-3"><Button variant="outline" onClick={() => setPreview({ subject: editing.subject, html: editing.bodyHtml })} leadingIcon={<Eye className="size-4" />}>Preview</Button><label className="flex items-center gap-2 text-sm text-body"><input type="checkbox" checked={editing.enabled} onChange={(event) => setEditing({ ...editing, enabled: event.target.checked })} />Enabled</label></div></div></Modal> : null}
    {preview ? <Modal open onClose={() => setPreview(null)} title={`Preview: ${preview.subject}`} size="xl"><iframe title="Email template preview" sandbox="" srcDoc={preview.html} className="h-[560px] w-full rounded-lg border border-line bg-white" /></Modal> : null}
    {cloneSource ? <Modal open onClose={() => setCloneSource(null)} title={`Clone ${cloneSource.name}`} footer={<><Button variant="outline" onClick={() => setCloneSource(null)}>Cancel</Button><Button busy={clone.isPending} disabled={!cloneKey || !cloneName} onClick={() => clone.mutate({ sourceTemplateKey: cloneSource.templateKey, templateKey: cloneKey.trim(), name: cloneName.trim() })} leadingIcon={<Plus className="size-4" />}>Create clone</Button></>}><div className="space-y-4"><FieldShell label="New template key" help="Lowercase letters, numbers, periods, hyphens, and underscores only."><Input value={cloneKey} onChange={(event) => setCloneKey(event.target.value)} /></FieldShell><FieldShell label="Template name"><Input value={cloneName} onChange={(event) => setCloneName(event.target.value)} /></FieldShell></div></Modal> : null}
    {viewLog ? <Modal open onClose={() => setViewLog(null)} title="Retained email record" size="xl"><div className="space-y-4"><div className="grid gap-3 text-sm sm:grid-cols-2"><p><strong>To:</strong> {viewLog.to ?? "Unavailable"}</p><p><strong>BCC:</strong> {viewLog.bcc ?? "None"}</p><p><strong>Status:</strong> {viewLog.status}</p><p><strong>Sent:</strong> {formatDateTime(viewLog.sentAt ?? viewLog.createdAt)}</p></div>{viewLog.detail ? <p className="rounded-lg bg-danger/10 p-3 text-sm text-danger">{viewLog.detail}</p> : null}{viewLog.bodyHtml ? <iframe title="Retained email copy" sandbox="" srcDoc={viewLog.bodyHtml} className="h-[520px] w-full rounded-lg border border-line bg-white" /> : <EmptyState icon={ShieldCheck} title="Message copy unavailable" description="This record predates encrypted message-copy retention." />}</div></Modal> : null}
    <ConfirmDialog open={purgeOpen} onClose={() => setPurgeOpen(false)} onConfirm={() => purge.mutate()} title="Purge expired email records?" message={`This permanently removes retained email copies older than the configured ${audit.data?.retentionDays ?? 365}-day retention period.`} confirmLabel="Purge expired records" variant="danger" busy={purge.isPending} />
  </>;
}
