import { useState } from "react";
import { BookOpen, CheckCircle2, Pencil, Plus, Send, Trash2 } from "lucide-react";
import { trpc, errorMessage } from "@/lib/trpc";
import { Button } from "@/components/ui/Button";
import { Input, Select, Textarea } from "@/components/ui/Field";
import { Badge, Card, CardHeader, EmptyState, Skeleton } from "@/components/ui/Surface";
import { ConfirmDialog, Modal } from "@/components/ui/Modal";
import { PageHeader } from "@/components/layout/PortalLayout";
import { useSession } from "@/lib/session";
import { useToast } from "@/components/ui/Toast";

type Article = { id: number; title: string; slug: string; category: string | null; excerpt: string | null; bodyMarkdown: string; status: "draft" | "pending_review" | "published" | "rejected"; authorUserId: number; submittedAt: Date | string | null; reviewedAt: Date | string | null; publishedAt: Date | string | null; updatedAt: Date | string };
type Form = { id?: number; title: string; slug: string; category: string; excerpt: string; bodyMarkdown: string; submitForApproval: boolean };
const blank = (): Form => ({ title: "", slug: "", category: "", excerpt: "", bodyMarkdown: "", submitForApproval: false });
const label = (status: Article["status"]) => ({ draft: "Draft", pending_review: "Pending approval", published: "Published", rejected: "Needs revision" }[status]);
const tone = (status: Article["status"]) => status === "published" ? "success" : status === "pending_review" ? "warning" : status === "rejected" ? "danger" : "neutral";

export function AdminKnowledgeBasePage() {
  const session = useSession(); const toast = useToast(); const utils = trpc.useUtils();
  const list = trpc.knowledgeBase.list.useQuery();
  const [editing, setEditing] = useState<Form | null>(null);
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const save = trpc.knowledgeBase.upsert.useMutation({ onSuccess() { void utils.knowledgeBase.list.invalidate(); setEditing(null); toast.success("Knowledge base article saved"); }, onError(error) { toast.error("Could not save article", errorMessage(error)); } });
  const review = trpc.knowledgeBase.review.useMutation({ onSuccess() { void utils.knowledgeBase.list.invalidate(); toast.success("Knowledge base approval updated"); }, onError(error) { toast.error("Could not update approval", errorMessage(error)); } });
  const remove = trpc.knowledgeBase.remove.useMutation({ onSuccess() { void utils.knowledgeBase.list.invalidate(); setDeleteId(null); toast.success("Knowledge base article deleted"); }, onError(error) { toast.error("Could not delete article", errorMessage(error)); } });
  const isAdmin = session.user?.role === "admin";
  const openEdit = (article: Article) => setEditing({ id: article.id, title: article.title, slug: article.slug, category: article.category ?? "", excerpt: article.excerpt ?? "", bodyMarkdown: article.bodyMarkdown, submitForApproval: article.status === "pending_review" });
  const create = () => setEditing(blank());
  if (list.isLoading) return <div className="space-y-4"><Skeleton className="h-12 w-72" /><Skeleton className="h-96 w-full" /></div>;
  return <><PageHeader title="Knowledge base" description="Draft customer guidance, submit articles for review, and publish only after administrator approval." actions={<Button variant="primary" leadingIcon={<Plus className="size-4" />} onClick={create}>New article</Button>} />
    <Card><CardHeader title="Article approval queue" description="Only articles marked Published are available in the customer portal knowledge base." />{(list.data ?? []).length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-line text-xs uppercase tracking-wide text-muted"><tr><th className="px-3 py-2">Article</th><th className="px-3 py-2">Category</th><th className="px-3 py-2">Approval</th><th className="px-3 py-2">Actions</th></tr></thead><tbody>{(list.data ?? []).map((article) => <tr key={article.id} className="border-b border-line/70"><td className="px-3 py-4"><p className="font-medium text-ink">{article.title}</p><p className="mt-1 font-mono text-xs text-muted">{article.slug}</p></td><td className="px-3 py-4">{article.category || "—"}</td><td className="px-3 py-4"><Badge tone={tone(article.status as Article["status"])}>{label(article.status as Article["status"])}</Badge></td><td className="px-3 py-4"><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" leadingIcon={<Pencil className="size-3.5" />} onClick={() => openEdit(article as Article)}>Edit</Button>{isAdmin && article.status !== "published" ? <Button size="sm" variant="outline" leadingIcon={<CheckCircle2 className="size-3.5" />} busy={review.isPending} onClick={() => review.mutate({ id: article.id, status: "published" })}>Approve & publish</Button> : null}{isAdmin && article.status === "published" ? <Button size="sm" variant="outline" busy={review.isPending} onClick={() => review.mutate({ id: article.id, status: "draft" })}>Unpublish</Button> : null}{isAdmin && article.status === "pending_review" ? <Button size="sm" variant="ghost" busy={review.isPending} onClick={() => review.mutate({ id: article.id, status: "rejected" })}>Request revision</Button> : null}{isAdmin ? <Button size="sm" variant="ghost" leadingIcon={<Trash2 className="size-3.5" />} onClick={() => setDeleteId(article.id)}>Delete</Button> : null}</div></td></tr>)}</tbody></table></div> : <EmptyState icon={BookOpen} title="No knowledge base articles" description="Create a draft, then submit it for administrator approval before customers can see it." action={<Button variant="primary" onClick={create}>Create article</Button>} />}</Card>
    {editing ? <Modal open onClose={() => setEditing(null)} title={editing.id ? "Edit knowledge base article" : "New knowledge base article"} size="xl" footer={<><Button variant="outline" onClick={() => setEditing(null)}>Cancel</Button><Button variant="primary" busy={save.isPending} disabled={editing.title.trim().length < 3 || editing.slug.trim().length < 3 || editing.bodyMarkdown.trim().length < 20} onClick={() => save.mutate({ id: editing.id, title: editing.title.trim(), slug: editing.slug.trim().toLowerCase(), category: editing.category.trim() || undefined, excerpt: editing.excerpt.trim() || undefined, bodyMarkdown: editing.bodyMarkdown.trim(), submitForApproval: editing.submitForApproval })}>{editing.submitForApproval ? "Save & submit for approval" : "Save draft"}</Button></>}><div className="space-y-4"><Input label="Title" value={editing.title} onChange={(event) => setEditing({ ...editing, title: event.target.value })} required /><Input label="URL slug" help="Lowercase words separated by hyphens, for example payment-and-checkout." value={editing.slug} onChange={(event) => setEditing({ ...editing, slug: event.target.value })} required /><Input label="Category" value={editing.category} onChange={(event) => setEditing({ ...editing, category: event.target.value })} placeholder="Orders, Billing, Portal access" /><Textarea label="Short summary" rows={3} value={editing.excerpt} onChange={(event) => setEditing({ ...editing, excerpt: event.target.value })} /><Textarea label="Article content (Markdown)" rows={18} value={editing.bodyMarkdown} onChange={(event) => setEditing({ ...editing, bodyMarkdown: event.target.value })} required /><Select label="Workflow" value={editing.submitForApproval ? "submit" : "draft"} onChange={(event) => setEditing({ ...editing, submitForApproval: event.target.value === "submit" })}><option value="draft">Save as draft</option><option value="submit">Submit for administrator approval</option></Select>{editing.submitForApproval ? <p className="rounded-lg bg-teal/10 p-3 text-sm text-body">Submitting does not publish the article. An administrator must approve it before customers can access it.</p> : null}</div></Modal> : null}
    <ConfirmDialog open={deleteId !== null} onClose={() => setDeleteId(null)} onConfirm={() => { if (deleteId !== null) remove.mutate({ id: deleteId }); }} title="Delete knowledge base article?" message="This permanently removes the article from the review queue and customer portal." confirmLabel="Delete article" variant="danger" busy={remove.isPending} />
  </>;
}
