import { useState } from "react";
import { CheckCircle2, ChevronLeft, ChevronRight, KeyRound, Mail, Network, ShieldCheck, Webhook } from "lucide-react";
import { trpc, errorMessage } from "@/lib/trpc";
import { Button } from "@/components/ui/Button";
import { Checkbox, FieldShell, Input, Select, Textarea } from "@/components/ui/Field";
import { Alert, Badge, Card, CardHeader } from "@/components/ui/Surface";
import { PageHeader } from "@/components/layout/PortalLayout";
import { useToast } from "@/components/ui/Toast";

const steps = ["Welcome", "Email", "Microsoft Entra ID", "Stripe", "Phase webhooks", "Access controls", "Finish"];
const validPublicId = /^RP-U-[A-F0-9]{12}$/i;

export function AdminPlatformSetupPage() {
  const toast = useToast();
  const utils = trpc.useUtils();
  const status = trpc.platformSetup.status.useQuery();
  const [step, setStep] = useState(0);
  const [transport, setTransport] = useState<"none" | "smtp" | "graph">("none");
  const [smtp, setSmtp] = useState({ host: "", port: "587", user: "", password: "", from: "no-reply@readypackets.com", replyTo: "", secure: false });
  const [graph, setGraph] = useState({ tenantId: "", clientId: "", clientSecret: "", sender: "" });
  const [entra, setEntra] = useState({ enabled: false, name: "Microsoft Entra ID", entryPoint: "", issuer: "", certificate: "", autoProvision: false, defaultRole: "staff" as "customer" | "staff" | "admin" });
  const [stripe, setStripe] = useState({ secretKey: "", publishableKey: "", webhookSecret: "" });
  const [p101, setP101] = useState({ enabled: false, url: "", secret: "" });
  const [p201, setP201] = useState({ enabled: false, url: "", secret: "" });
  const [ipText, setIpText] = useState("");
  const [loginWhitelistEnabled, setLoginWhitelistEnabled] = useState(false);
  const [loginWhitelistText, setLoginWhitelistText] = useState("");

  const refresh = async () => { await utils.platformSetup.status.invalidate(); };
  const saveEmail = trpc.platformSetup.saveEmail.useMutation({ onSuccess: async () => { await refresh(); toast.success("Email configuration saved"); setStep(2); }, onError: (error) => toast.error("Email configuration could not be saved", errorMessage(error)) });
  const saveEntra = trpc.platformSetup.saveEntra.useMutation({ onSuccess: async () => { await refresh(); toast.success("Microsoft Entra ID configuration saved"); setStep(3); }, onError: (error) => toast.error("Microsoft Entra ID configuration could not be saved", errorMessage(error)) });
  const saveStripe = trpc.platformSetup.saveStripe.useMutation({ onSuccess: async () => { await refresh(); toast.success("Stripe configuration saved"); setStep(4); }, onError: (error) => toast.error("Stripe configuration could not be saved", errorMessage(error)) });
  const saveWebhooks = trpc.platformSetup.savePhaseWebhooks.useMutation({ onSuccess: async () => { await refresh(); toast.success("Phase webhook configuration saved"); setStep(5); }, onError: (error) => toast.error("Phase webhooks could not be saved", errorMessage(error)) });
  const saveAccess = trpc.platformSetup.saveAccess.useMutation({ onSuccess: async () => { await refresh(); toast.success("Access controls saved"); setStep(6); }, onError: (error) => toast.error("Access controls could not be saved", errorMessage(error)) });
  const complete = trpc.platformSetup.complete.useMutation({ onSuccess: async () => { await refresh(); toast.success("Platform setup marked complete", "You can return to this wizard any time from the administrator menu."); }, onError: (error) => toast.error("Setup completion could not be saved", errorMessage(error)) });

  const next = () => setStep((value) => Math.min(value + 1, steps.length - 1));
  const previous = () => setStep((value) => Math.max(value - 1, 0));
  const stepLabel = `${step + 1} of ${steps.length}`;
  const parseLines = (value: string) => value.split(/\r?\n|,/).map((item) => item.trim()).filter(Boolean);

  return <>
    <PageHeader title="Platform setup wizard" description="Configure essential ReadyPackets integrations and access controls from one guided administrator-only workflow." />
    <Alert tone="warning" className="mb-6" title="Keep a recovery path">Do not enable Microsoft Entra ID, an IP allowlist, or the account login whitelist until you have confirmed that your local administrator account and current address can still sign in.</Alert>
    <div className="mb-6 overflow-x-auto"><ol className="flex min-w-max items-center gap-2">{steps.map((label, index) => <li key={label} className={`flex items-center gap-2 ${index === step ? "text-teal-dark" : index < step ? "text-success" : "text-muted"}`}><span className={`flex size-7 items-center justify-center rounded-full border text-xs font-bold ${index === step ? "border-teal bg-teal text-white" : index < step ? "border-success bg-success text-white" : "border-line bg-surface"}`}>{index < step ? <CheckCircle2 className="size-4" /> : index + 1}</span><span className="text-sm font-medium">{label}</span>{index < steps.length - 1 ? <span className="mx-1 h-px w-7 bg-line" /> : null}</li>)}</ol></div>
    {status.data?.completedAt ? <Alert tone="success" className="mb-6" title="Initial setup previously completed">Completed {new Date(status.data.completedAt).toLocaleString()}. You can safely revisit and revise any configuration step.</Alert> : null}

    {step === 0 ? <Card><CardHeader title="Welcome to ReadyPackets setup" description="This optional guided flow collects configuration already available elsewhere in the administrator panel. Secrets are write-only and encrypted at rest." /><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[{ label: "Email", ready: status.data?.emailTransport !== "none" }, { label: "Entra", ready: status.data?.entraEnabled }, { label: "Stripe", ready: status.data?.stripeReady }, { label: "P101 webhook", ready: status.data?.p101Configured }, { label: "P201 webhook", ready: status.data?.p201Configured }, { label: "Login allowlist", ready: status.data?.loginWhitelistEnabled }].map((item) => <div key={item.label} className="flex items-center justify-between rounded-lg border border-line p-3"><span className="text-sm font-medium text-ink">{item.label}</span><Badge tone={item.ready ? "success" : "neutral"}>{item.ready ? "configured" : "optional"}</Badge></div>)}</div><div className="mt-6 flex justify-end"><Button onClick={next} trailingIcon={<ChevronRight className="size-4" />}>Start setup</Button></div></Card> : null}

    {step === 1 ? <Card><CardHeader title="Outbound email" description="Choose SMTP or Microsoft Graph. Select not configured only when you intentionally want to defer sending portal notifications." /><div className="mt-5 space-y-4"><FieldShell label="Delivery method"><Select value={transport} onChange={(event) => setTransport(event.target.value as typeof transport)} options={[{ value: "none", label: "Not configured yet" }, { value: "smtp", label: "SMTP" }, { value: "graph", label: "Microsoft Graph API" }]} /></FieldShell>{transport === "smtp" ? <div className="grid gap-4 sm:grid-cols-2"><Input label="SMTP host" value={smtp.host} onChange={(event) => setSmtp({ ...smtp, host: event.target.value })} placeholder="smtp.example.com" /><Input label="Port" type="number" value={smtp.port} onChange={(event) => setSmtp({ ...smtp, port: event.target.value })} /><Input label="Username" value={smtp.user} onChange={(event) => setSmtp({ ...smtp, user: event.target.value })} /><Input label="Password" type="password" value={smtp.password} onChange={(event) => setSmtp({ ...smtp, password: event.target.value })} placeholder="Leave blank to preserve an existing secret" /><Input label="From address" type="email" value={smtp.from} onChange={(event) => setSmtp({ ...smtp, from: event.target.value })} /><Input label="Reply-to address" type="email" value={smtp.replyTo} onChange={(event) => setSmtp({ ...smtp, replyTo: event.target.value })} /><Checkbox label="Use implicit TLS" checked={smtp.secure} onChange={(event) => setSmtp({ ...smtp, secure: event.target.checked })} /></div> : null}{transport === "graph" ? <div className="grid gap-4 sm:grid-cols-2"><Input label="Tenant ID" value={graph.tenantId} onChange={(event) => setGraph({ ...graph, tenantId: event.target.value })} /><Input label="Client ID" value={graph.clientId} onChange={(event) => setGraph({ ...graph, clientId: event.target.value })} /><Input label="Client secret" type="password" value={graph.clientSecret} onChange={(event) => setGraph({ ...graph, clientSecret: event.target.value })} placeholder="Leave blank to preserve an existing secret" /><Input label="Sender address" type="email" value={graph.sender} onChange={(event) => setGraph({ ...graph, sender: event.target.value })} /></div> : null}</div><WizardButtons onBack={previous} onSkip={next} skipLabel="Skip for now" onSave={() => saveEmail.mutate({ transport, smtp: { ...smtp, port: Number(smtp.port) || 587 }, graph })} busy={saveEmail.isPending} saveLabel="Save email setup" /></Card> : null}

    {step === 2 ? <Card><CardHeader title="Microsoft Entra ID" description="Configure SAML single sign-on. Keep this disabled until you have tested the Reply URL and certificate in Entra." /><div className="mt-5 space-y-4"><Checkbox label="Enable Microsoft Entra ID sign-in after saving" checked={entra.enabled} onChange={(event) => setEntra({ ...entra, enabled: event.target.checked })} /><div className="grid gap-4 sm:grid-cols-2"><Input label="Configuration name" value={entra.name} onChange={(event) => setEntra({ ...entra, name: event.target.value })} /><Input label="Sign-on URL" type="url" value={entra.entryPoint} onChange={(event) => setEntra({ ...entra, entryPoint: event.target.value })} placeholder="https://login.microsoftonline.com/..." /><Input label="Entity ID / issuer" value={entra.issuer} onChange={(event) => setEntra({ ...entra, issuer: event.target.value })} /><Select label="Automatic new-user role" value={entra.defaultRole} onChange={(event) => setEntra({ ...entra, defaultRole: event.target.value as typeof entra.defaultRole })} options={[{ value: "customer", label: "Customer" }, { value: "staff", label: "Staff" }, { value: "admin", label: "Administrator" }]} /><Checkbox label="Automatically provision assigned SAML users" checked={entra.autoProvision} onChange={(event) => setEntra({ ...entra, autoProvision: event.target.checked })} /></div><Textarea label="Base64 certificate" rows={7} value={entra.certificate} onChange={(event) => setEntra({ ...entra, certificate: event.target.value })} placeholder="Paste the certificate; leave blank only to retain the existing value." /><Alert tone="info">Reply URL: <code>{window.location.origin}/api/saml/acs</code></Alert></div><WizardButtons onBack={previous} onSkip={next} skipLabel="Skip for now" onSave={() => saveEntra.mutate(entra)} busy={saveEntra.isPending} saveLabel="Save Entra setup" /></Card> : null}

    {step === 3 ? <Card><CardHeader title="Stripe payments" description="Enter the Stripe API keys and webhook signing secret. The webhook secret is required before ReadyPackets treats a returned checkout as paid." /><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="Secret key" type="password" value={stripe.secretKey} onChange={(event) => setStripe({ ...stripe, secretKey: event.target.value })} placeholder="sk_live_… or sk_test_…" /><Input label="Publishable key" value={stripe.publishableKey} onChange={(event) => setStripe({ ...stripe, publishableKey: event.target.value })} placeholder="pk_live_… or pk_test_…" /><Input className="sm:col-span-2" label="Webhook signing secret" type="password" value={stripe.webhookSecret} onChange={(event) => setStripe({ ...stripe, webhookSecret: event.target.value })} placeholder="whsec_…" /></div><Alert tone="info" className="mt-4">Register this webhook in Stripe: <code>{window.location.origin}/api/stripe/webhook</code></Alert><WizardButtons onBack={previous} onSkip={next} skipLabel="Skip for now" onSave={() => saveStripe.mutate(stripe)} busy={saveStripe.isPending} saveLabel="Save Stripe setup" /></Card> : null}

    {step === 4 ? <Card><CardHeader title="Phase-start webhooks" description="Optionally deliver signed P101 and P201 lifecycle payloads to downstream systems. Only HTTPS endpoints are accepted." /><div className="mt-5 grid gap-5 lg:grid-cols-2"><WebhookFields title="Phase I Start — P101" value={p101} onChange={setP101} /><WebhookFields title="Phase II Start — P201" value={p201} onChange={setP201} /></div><WizardButtons onBack={previous} onSkip={next} skipLabel="Skip for now" onSave={() => saveWebhooks.mutate({ p101: p101.enabled ? p101 : undefined, p201: p201.enabled ? p201 : undefined })} busy={saveWebhooks.isPending} saveLabel="Save phase webhooks" disabled={!p101.enabled && !p201.enabled} /></Card> : null}

    {step === 5 ? <Card><CardHeader title="IP and account login allowlists" description="IP allowlist entries are added with all-access scope. The optional account login whitelist blocks local password, customer magic-link, and SAML sign-in for accounts not listed." /><div className="mt-5 space-y-5"><Textarea label="IP addresses, CIDR blocks, or IPv4 ranges" help="Enter one per line. Examples: 203.0.113.8, 203.0.113.0/24, 203.0.113.10-203.0.113.25." rows={5} value={ipText} onChange={(event) => setIpText(event.target.value)} /><Checkbox label="Enable the account login whitelist" checked={loginWhitelistEnabled} onChange={(event) => setLoginWhitelistEnabled(event.target.checked)} /><Textarea label="Allowed public customer / user IDs" help="One ReadyPackets ID per line, for example RP-U-ABCDEF123456. Include your current administrator ID before enabling the control." rows={5} value={loginWhitelistText} onChange={(event) => setLoginWhitelistText(event.target.value.toUpperCase())} /><Alert tone="warning">Do not enable the account login whitelist until the current administrator account’s public ID is included. Existing sessions remain active, but future sign-in will be restricted.</Alert></div><WizardButtons onBack={previous} onSkip={next} skipLabel="Skip for now" onSave={() => { const ids = parseLines(loginWhitelistText); const invalid = ids.find((id) => !validPublicId.test(id)); if (invalid) { toast.error("Invalid public customer / user ID", invalid); return; } saveAccess.mutate({ ipPatterns: parseLines(ipText), loginWhitelistEnabled, loginWhitelistPublicIds: ids }); }} busy={saveAccess.isPending} saveLabel="Save access controls" /></Card> : null}

    {step === 6 ? <Card><CardHeader title="Setup review" description="You can modify any section later from the relevant administrator workspace or by reopening this wizard." /><div className="mt-5 space-y-3">{[{ label: "Email delivery", value: status.data?.emailTransport === "none" ? "not configured" : status.data?.emailTransport }, { label: "Microsoft Entra ID", value: status.data?.entraEnabled ? "enabled" : "not enabled" }, { label: "Stripe", value: status.data?.stripeReady ? "ready" : "not fully configured" }, { label: "Phase webhooks", value: `${status.data?.p101Configured ? "P101" : ""}${status.data?.p101Configured && status.data?.p201Configured ? ", " : ""}${status.data?.p201Configured ? "P201" : ""}` || "not configured" }, { label: "Account login whitelist", value: status.data?.loginWhitelistEnabled ? "enabled" : "not enabled" }].map((item) => <div key={item.label} className="flex justify-between rounded-lg border border-line p-3"><span className="font-medium text-ink">{item.label}</span><span className="text-body">{item.value}</span></div>)}</div><div className="mt-6 flex flex-wrap justify-between gap-3"><Button variant="outline" onClick={() => setStep(0)} leadingIcon={<ChevronLeft className="size-4" />}>Review steps</Button><Button busy={complete.isPending} onClick={() => complete.mutate()} leadingIcon={<ShieldCheck className="size-4" />}>Mark setup complete</Button></div></Card> : null}
    <p className="mt-5 text-center text-xs text-muted">{stepLabel} · Setup changes are recorded in the activity trail. Secret values are not returned to the browser after saving.</p>
  </>;
}

function WizardButtons({ onBack, onSkip, onSave, busy, saveLabel, skipLabel, disabled = false }: { onBack: () => void; onSkip: () => void; onSave: () => void; busy: boolean; saveLabel: string; skipLabel: string; disabled?: boolean }) {
  return <div className="mt-6 flex flex-wrap justify-between gap-3"><Button variant="outline" onClick={onBack} leadingIcon={<ChevronLeft className="size-4" />}>Back</Button><div className="flex gap-3"><Button variant="ghost" onClick={onSkip}>{skipLabel}</Button><Button onClick={onSave} busy={busy} disabled={disabled} trailingIcon={<ChevronRight className="size-4" />}>{saveLabel}</Button></div></div>;
}

function WebhookFields({ title, value, onChange }: { title: string; value: { enabled: boolean; url: string; secret: string }; onChange: (value: { enabled: boolean; url: string; secret: string }) => void }) {
  return <div className="rounded-lg border border-line p-4"><h3 className="font-semibold text-ink">{title}</h3><div className="mt-4 space-y-4"><Checkbox label="Enable this phase-start webhook" checked={value.enabled} onChange={(event) => onChange({ ...value, enabled: event.target.checked })} /><Input label="Destination URL" type="url" disabled={!value.enabled} value={value.url} onChange={(event) => onChange({ ...value, url: event.target.value })} placeholder="https://automation.example.com/webhooks/readypackets" /><Input label="HMAC secret" type="password" disabled={!value.enabled} value={value.secret} onChange={(event) => onChange({ ...value, secret: event.target.value })} placeholder="Leave blank to preserve an existing secret" /></div></div>;
}
