import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, FileSearch, GitBranch, History, KeyRound, RefreshCw, RotateCcw, ShieldAlert, UploadCloud } from "lucide-react";
import { trpc, errorMessage } from "@/lib/trpc";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Field";
import { Card, CardHeader, Badge, EmptyState, Skeleton } from "@/components/ui/Surface";
import { ConfirmDialog, Modal } from "@/components/ui/Modal";
import { PageHeader } from "@/components/layout/PortalLayout";
import { useToast } from "@/components/ui/Toast";

const STATUS_TONES: Record<string, "success" | "warning" | "danger" | "neutral"> = { scanned: "neutral", approved: "warning", running: "warning", completed: "success", failed: "danger", rolled_back: "danger" };
type Run = { id: number; repository: string; branch: string; fromCommit: string; targetCommit: string; status: string; changedFiles: unknown; scanSummary: unknown; riskSummary: unknown; backupFilename: string | null; rollbackSnapshot: string | null; output: string | null; createdAt: string };

function asArray(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function asRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }

export function AdminPlatformUpdates() {
  const toast = useToast(); const utils = trpc.useUtils();
  const settings = trpc.platformUpdates.settings.useQuery(undefined, { retry: false });
  const runs = trpc.platformUpdates.list.useQuery(undefined, { retry: false });
  const [repository, setRepository] = useState(""); const [branch, setBranch] = useState("main"); const [pat, setPat] = useState("");
  const [selected, setSelected] = useState<Run | null>(null); const [approval, setApproval] = useState<Run | null>(null); const [upgrade, setUpgrade] = useState<Run | null>(null); const [rollback, setRollback] = useState<Run | null>(null); const [phrase, setPhrase] = useState("");
  useEffect(() => { if (settings.data) { setRepository(settings.data.repository); setBranch(settings.data.branch); } }, [settings.data]);
  const save = trpc.platformUpdates.saveSettings.useMutation({ onSuccess: () => { setPat(""); void utils.platformUpdates.settings.invalidate(); toast.success("Private repository settings saved"); }, onError: (error) => toast.error("Could not save settings", errorMessage(error)) });
  const scan = trpc.platformUpdates.scan.useMutation({ onSuccess: (result) => { void utils.platformUpdates.list.invalidate(); toast.success("Change scan complete", `${result.summary.filesChanged} files changed; review before approving.`); }, onError: (error) => toast.error("Could not scan repository", errorMessage(error)) });
  const approve = trpc.platformUpdates.approve.useMutation({ onSuccess: () => { setApproval(null); setPhrase(""); void utils.platformUpdates.list.invalidate(); toast.success("Release approved", "A second confirmation is required before installation."); }, onError: (error) => toast.error("Could not approve release", errorMessage(error)) });
  const execute = trpc.platformUpdates.execute.useMutation({ onSuccess: () => { setUpgrade(null); setPhrase(""); void utils.platformUpdates.list.invalidate(); void utils.platformUpdates.settings.invalidate(); toast.success("Upgrade completed", "The service was rebuilt, restarted, and health checked. Review the run record."); }, onError: (error) => toast.error("Upgrade failed", errorMessage(error)) });
  const restore = trpc.platformUpdates.rollback.useMutation({ onSuccess: () => { setRollback(null); setPhrase(""); void utils.platformUpdates.list.invalidate(); toast.success("Rollback completed", "The pre-upgrade application and database snapshot were restored."); }, onError: (error) => toast.error("Rollback failed", errorMessage(error)) });
  const rows = (runs.data ?? []) as Run[];
  const latest = useMemo(() => rows[0] ?? null, [rows]);
  if (settings.isLoading || runs.isLoading) return <div className="space-y-4"><Skeleton className="h-12 w-72" /><Skeleton className="h-96 w-full" /></div>;
  return <><PageHeader title="Platform updates" description="Scan a private GitHub repository, review exact changes, explicitly approve a release, and keep a pre-upgrade rollback snapshot." actions={<Button variant="outline" onClick={() => { void settings.refetch(); void runs.refetch(); }} leadingIcon={<RefreshCw className="size-4" />}>Refresh</Button>} />
    <div className="mb-6 grid gap-4 md:grid-cols-3"><Card className="p-4"><p className="text-sm text-muted">Current deployed commit</p><p className="mt-1 break-all font-mono text-sm font-semibold text-ink">{settings.data?.status.currentCommit ?? "Unknown"}</p></Card><Card className="p-4"><p className="text-sm text-muted">Service status</p><div className="mt-2"><Badge tone={settings.data?.status.serviceActive ? "success" : "danger"}>{settings.data?.status.serviceActive ? "Healthy" : "Not active"}</Badge></div></Card><Card className="p-4"><p className="text-sm text-muted">Latest update run</p><p className="mt-1 font-semibold text-ink">{latest ? `${latest.status} · ${latest.targetCommit.slice(0, 12)}` : "No scans yet"}</p></Card></div>
    <Card><CardHeader title="Private repository connection" description="The access token is encrypted at rest, never returned to the browser, and is supplied to the server-side update worker only through standard input. Use a fine-grained GitHub token restricted to this repository’s read-only Contents access." /><div className="mt-4 grid gap-4 lg:grid-cols-3"><Input label="Repository" value={repository} onChange={(event) => setRepository(event.target.value)} placeholder="owner/repository" /><Input label="Branch" value={branch} onChange={(event) => setBranch(event.target.value)} placeholder="main" /><Input label={settings.data?.hasToken ? "Replace access token (optional)" : "GitHub access token"} type="password" value={pat} onChange={(event) => setPat(event.target.value)} placeholder={settings.data?.hasToken ? "Stored securely — leave blank to keep" : "github_pat_..."} /></div><div className="mt-4 flex flex-wrap gap-3"><Button variant="primary" busy={save.isPending} disabled={!repository || !branch || (!settings.data?.hasToken && pat.length < 20)} leadingIcon={<KeyRound className="size-4" />} onClick={() => save.mutate({ repository, branch, pat: pat || undefined })}>Save connection</Button><Button variant="outline" busy={scan.isPending} disabled={!settings.data?.hasToken && pat.length < 20} leadingIcon={<FileSearch className="size-4" />} onClick={() => scan.mutate({ repository: repository || undefined, branch: branch || undefined })}>Scan for changes</Button></div><p className="mt-3 text-xs text-muted">Scanning does not modify production. A scan records changed files, migration and dependency indicators, and high-risk paths for administrator review.</p></Card>
    <Card className="mt-6"><CardHeader title="Reviewed update runs" description="Every scan, approval, installation, and rollback is retained in the administrative activity record." />{rows.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-b border-line text-xs uppercase tracking-wide text-muted"><tr><th className="px-3 py-2">Target</th><th className="px-3 py-2">Repository</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Created</th><th className="px-3 py-2 text-right">Actions</th></tr></thead><tbody>{rows.map((run) => <tr key={run.id} className="border-b border-line/70"><td className="px-3 py-3 font-mono text-xs text-ink">{run.targetCommit.slice(0, 12)}</td><td className="px-3 py-3"><p className="font-medium text-ink">{run.repository}</p><p className="text-xs text-muted">{run.branch} · from {run.fromCommit.slice(0, 12)}</p></td><td className="px-3 py-3"><Badge tone={STATUS_TONES[run.status] ?? "neutral"}>{run.status.replaceAll("_", " ")}</Badge></td><td className="px-3 py-3 text-muted">{new Date(run.createdAt).toLocaleString()}</td><td className="px-3 py-3"><div className="flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={() => setSelected(run)} leadingIcon={<History className="size-3.5" />}>Review</Button>{run.status === "scanned" ? <Button size="sm" variant="outline" onClick={() => setApproval(run)} leadingIcon={<CheckCircle2 className="size-3.5" />}>Approve</Button> : null}{run.status === "approved" ? <Button size="sm" variant="primary" onClick={() => setUpgrade(run)} leadingIcon={<UploadCloud className="size-3.5" />}>Upgrade</Button> : null}{run.status === "completed" ? <Button size="sm" variant="danger" onClick={() => setRollback(run)} leadingIcon={<RotateCcw className="size-3.5" />}>Rollback</Button> : null}</div></td></tr>)}</tbody></table></div> : <EmptyState icon={GitBranch} title="No update scans" description="Save a private repository connection and scan for a candidate release before any upgrade can be approved." />}</Card>
    <Modal open={selected !== null} onClose={() => setSelected(null)} title={selected ? `Release review · ${selected.targetCommit.slice(0, 12)}` : "Release review"} description="Review change indicators and paths before approving an upgrade."><div className="space-y-4">{selected ? <><div className="grid gap-3 sm:grid-cols-3"><Card className="p-3"><p className="text-xs text-muted">Files changed</p><p className="text-lg font-bold text-ink">{String(asRecord(selected.scanSummary).filesChanged ?? "—")}</p></Card><Card className="p-3"><p className="text-xs text-muted">Insertions</p><p className="text-lg font-bold text-ink">{String(asRecord(selected.scanSummary).insertions ?? "—")}</p></Card><Card className="p-3"><p className="text-xs text-muted">Deletions</p><p className="text-lg font-bold text-ink">{String(asRecord(selected.scanSummary).deletions ?? "—")}</p></Card></div><Card className="border-warning/40 bg-warning/5 p-4"><div className="flex gap-3"><ShieldAlert className="mt-0.5 size-5 shrink-0 text-warning" /><div><p className="font-semibold text-ink">Risk indicators</p><p className="mt-1 text-sm text-muted">Dependency changed: {String(asRecord(selected.riskSummary).dependencyFilesChanged ?? false)} · Migration changed: {String(asRecord(selected.riskSummary).migrationFilesChanged ?? false)} · Deployment changed: {String(asRecord(selected.riskSummary).deploymentFilesChanged ?? false)}</p></div></div></Card><div><p className="mb-2 text-sm font-semibold text-ink">Changed paths</p><pre className="max-h-72 overflow-auto rounded-lg border border-line bg-surface-subtle p-3 text-xs text-ink">{asArray(selected.changedFiles).join("\n") || "No file list available."}</pre></div></> : null}</div></Modal>
    <Modal open={approval !== null} onClose={() => { setApproval(null); setPhrase(""); }} title="Approve scanned release" description={approval ? `Type APPROVE ${approval.targetCommit.slice(0, 12)} to approve this immutable scan.` : ""} footer={<><Button variant="outline" onClick={() => { setApproval(null); setPhrase(""); }}>Cancel</Button><Button variant="primary" busy={approve.isPending} disabled={!approval || phrase !== `APPROVE ${approval.targetCommit.slice(0, 12)}`} onClick={() => approval && approve.mutate({ id: approval.id, confirmation: phrase })}>Approve release</Button></>}><Input label="Approval phrase" value={phrase} onChange={(event) => setPhrase(event.target.value)} autoComplete="off" /></Modal>
    <Modal open={upgrade !== null} onClose={() => { setUpgrade(null); setPhrase(""); }} title="Install approved release" description={upgrade ? `A pre-upgrade application and database snapshot will be created. Type UPGRADE ${upgrade.targetCommit.slice(0, 12)} to run tests, deploy, health-check, and retain rollback material.` : ""} footer={<><Button variant="outline" onClick={() => { setUpgrade(null); setPhrase(""); }}>Cancel</Button><Button variant="danger" busy={execute.isPending} disabled={!upgrade || phrase !== `UPGRADE ${upgrade.targetCommit.slice(0, 12)}`} onClick={() => upgrade && execute.mutate({ id: upgrade.id, confirmation: phrase })}>Install and restart</Button></>}><Input label="Upgrade phrase" value={phrase} onChange={(event) => setPhrase(event.target.value)} autoComplete="off" /></Modal>
    <Modal open={rollback !== null} onClose={() => { setRollback(null); setPhrase(""); }} title="Rollback completed release" description={rollback ? `This restores the entire pre-upgrade application and database snapshot. Data created after the upgrade will be replaced. Type ROLLBACK ${rollback.id} to continue.` : ""} footer={<><Button variant="outline" onClick={() => { setRollback(null); setPhrase(""); }}>Cancel</Button><Button variant="danger" busy={restore.isPending} disabled={!rollback || phrase !== `ROLLBACK ${rollback.id}`} onClick={() => rollback && restore.mutate({ id: rollback.id, confirmation: phrase })}>Restore snapshot</Button></>}><Input label="Rollback phrase" value={phrase} onChange={(event) => setPhrase(event.target.value)} autoComplete="off" /></Modal>
  </>;
}
