/**
 * PWA install and update prompts.
 *
 * Two separate components:
 *   - PwaInstallPrompt: shows a banner when the browser fires beforeinstallprompt,
 *     letting the user add the portal to their home screen.
 *   - PwaUpdatePrompt: shows a banner when the service worker has an update waiting,
 *     letting the user reload to apply it.
 *
 * Both are registered once in main.tsx and rendered at the root level.
 */
import { useEffect, useState } from "react";
import { Button } from "./ui/Button";

// ---------------------------------------------------------------------------
// Install prompt
// ---------------------------------------------------------------------------

interface BeforeInstallPromptEvent extends Event {
  prompt(): Promise<void>;
  userChoice: Promise<{ outcome: "accepted" | "dismissed" }>;
}

export function PwaInstallPrompt() {
  const [deferred, setDeferred] = useState<BeforeInstallPromptEvent | null>(null);
  const [dismissed, setDismissed] = useState(false);

  useEffect(() => {
    const handler = (e: Event) => {
      e.preventDefault();
      setDeferred(e as BeforeInstallPromptEvent);
    };
    window.addEventListener("beforeinstallprompt", handler);
    return () => window.removeEventListener("beforeinstallprompt", handler);
  }, []);

  if (!deferred || dismissed) return null;

  async function install() {
    if (!deferred) return;
    await deferred.prompt();
    const { outcome } = await deferred.userChoice;
    if (outcome === "accepted") setDeferred(null);
    else setDismissed(true);
  }

  return (
    <div
      role="banner"
      className="fixed bottom-4 left-4 right-4 sm:left-auto sm:right-4 sm:w-80 z-50
                 bg-brand-navy text-white rounded-xl shadow-2xl p-4 flex items-start gap-3"
    >
      <div className="shrink-0 mt-0.5">
        <img src="/brand/icon-192.png" alt="" className="w-10 h-10 rounded-lg" />
      </div>
      <div className="flex-1 min-w-0">
        <p className="font-semibold text-sm">Add to home screen</p>
        <p className="text-xs text-white/70 mt-0.5">
          Install ReadyPackets for quick access to your portal.
        </p>
        <div className="flex gap-2 mt-3">
          <Button size="sm" onClick={install} className="bg-brand-teal hover:bg-brand-teal/90 text-white border-0">
            Install
          </Button>
          <Button size="sm" variant="ghost" onClick={() => setDismissed(true)} className="text-white/70 hover:text-white">
            Not now
          </Button>
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Update prompt
// ---------------------------------------------------------------------------

export function PwaUpdatePrompt() {
  const [updateReady, setUpdateReady] = useState(false);
  const [registration, setRegistration] = useState<ServiceWorkerRegistration | null>(null);

  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;

    // Register the service worker generated by vite-plugin-pwa.
    navigator.serviceWorker
      .register("/sw.js", { scope: "/" })
      .then((reg) => {
        setRegistration(reg);

        // An update is already waiting.
        if (reg.waiting) {
          setUpdateReady(true);
          return;
        }

        // Listen for a new service worker installing.
        reg.addEventListener("updatefound", () => {
          const installing = reg.installing;
          if (!installing) return;
          installing.addEventListener("statechange", () => {
            if (installing.state === "installed" && navigator.serviceWorker.controller) {
              setUpdateReady(true);
            }
          });
        });
      })
      .catch(() => {
        // Service worker registration failed — not a fatal error.
      });

    // Reload when the new service worker takes control.
    navigator.serviceWorker.addEventListener("controllerchange", () => {
      window.location.reload();
    });
  }, []);

  if (!updateReady) return null;

  function applyUpdate() {
    if (registration?.waiting) {
      registration.waiting.postMessage({ type: "SKIP_WAITING" });
    }
  }

  return (
    <div
      role="alert"
      className="fixed top-4 left-4 right-4 sm:left-auto sm:right-4 sm:w-80 z-50
                 bg-white border border-brand-teal/30 rounded-xl shadow-2xl p-4 flex items-start gap-3"
    >
      <div className="shrink-0 mt-0.5 text-brand-teal">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
          <polyline points="17 8 12 3 7 8"/>
          <line x1="12" y1="3" x2="12" y2="15"/>
        </svg>
      </div>
      <div className="flex-1 min-w-0">
        <p className="font-semibold text-sm text-brand-navy">Update available</p>
        <p className="text-xs text-gray-500 mt-0.5">
          A new version of the portal is ready.
        </p>
        <div className="flex gap-2 mt-3">
          <Button size="sm" onClick={applyUpdate}>
            Reload and update
          </Button>
          <Button size="sm" variant="ghost" onClick={() => setUpdateReady(false)} className="text-gray-500">
            Later
          </Button>
        </div>
      </div>
    </div>
  );
}
